name: Test

on:
  workflow_dispatch:

  push:
    branches:
      - main
  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container: node:18.16.0

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      libsql:
        image: ghcr.io/libsql/sqld:latest
        ports:
          - 8888:8080

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18.16.0
      #     cache: npm

      - name: Install Wing
        run: npm i -g winglang

      - name: Install
        run: npm ci

      - name: Test libsql
        run: curl http://localhost:8888/health

      - name: Test examples
        run: ./test example_turso.main.w
